### ISSUE TITLE
Secret volume mount does not work

### ISSUE THREAD

**Issue by dealancer** [mittwald/kube-httpcache#12]
I am seeing this error message:

```
Error: failed to start container "varnish": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/91577ebe-37e6-11ea-803a-025000000001/volumes/kubernetes.io~secret/secret\\\" to rootfs \\\"/var/lib/docker/overlay2/ebb6aca1feaa9bc32308fb66911c9119e7b82492ab6daf5d1c7e5279c9cc1776/merged\\\" at \\\"/var/lib/docker/overlay2/ebb6aca1feaa9bc32308fb66911c9119e7b82492ab6daf5d1c7e5279c9cc1776/merged/etc/varnish/secret\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

Looks like something is wrong with secret volume mount. Any ideas how to fix it?

**Comment by dealancer** [comment]
After some time of debugging I figured out that `/etc/varnish/secret` is a file and it could not be mount to a directory. The deployment configuration needs to be changed to:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: cache
        image: quay.io/spaces/kube-httpcache:stable
        imagePullPolicy: Always
        args:
        - -admin-addr=0.0.0.0
        - -admin-port=6083
        - -varnish-secret-file=/etc/varnish/scrt/secret
        - -varnish-vcl-template=/etc/varnish/tmpl/default.vcl.tmpl
        - -varnish-storage=malloc,128M
        volumeMounts:
        - name: template
          mountPath: /etc/varnish/tmpl
        - name: secret
          mountPath: /etc/varnish/scrt
      serviceAccountName: kube-httpcache  # when using RBAC
      volumes:
      - name: template
        configMap:
          name: vcl-template
      - name: secret
        secret:
          secretName: varnish-secret
```
