### ISSUE TITLE
Varnish responds with 503 after a few hours

### ISSUE THREAD

**Issue by zzvara** [mittwald/kube-httpcache#33]
**Describe the bug**
Having Varnish and the backend (Magento 2.3.5) running for a few hours, after a while, Varnish responds with 503.

**To Reproduce**
1. Deploy Magento 2.3.5 from Bitnami Helm Charts.
2. Deploy Varnish as follows:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: magento-varnish
  namespace: production
  labels:
    app: cache
spec:
  serviceName: magento-varnish
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: cache
          image: quay.io/mittwald/kube-httpcache:stable
          imagePullPolicy: Always
          args:
            - -admin-addr=0.0.0.0
            - -admin-port=6083
            - -signaller-enable=true
            - -signaller-port=8090
            - -frontend-watch=false
            - -frontend-namespace=$(NAMESPACE)
            - -frontend-service=magento-varnish
            - -backend-watch=false
            - -backend-namespace=$(NAMESPACE)
            - -backend-service=magento
            - -varnish-secret-file=/etc/varnish/k8s-secret/secret
            - -varnish-vcl-template=/etc/varnish/tmpl/default.vcl.tmpl
            - -varnish-storage=malloc,512M
            - -varnish-additional-parameters=http_resp_size=98304
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: template
              mountPath: /etc/varnish/tmpl
            - name: secret
              mountPath: /etc/varnish/k8s-secret
          readinessProbe:
            httpGet:
              port: 80
              httpHeaders:
                - name: Host
                  value: example.com
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 80
              httpHeaders:
                - name: Host
                  value: example.com
            initialDelaySeconds: 10
            periodSeconds: 5
      serviceAccountName: magento-varnish
      restartPolicy: Always
      volumes:
        - name: template
          configMap:
            name: magento-varnish-configuration
        - name: secret
          secret:
            secretName: magento-varnish
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: magento-varnish-configuration
  namespace: production
data:
  default.vcl.tmpl: |
    # VCL version 5.0 is not supported so it should be 4.0 even though actually used Varnish version is 6
    vcl 4.0;

    import std;
    # The minimal Varnish version is 6.0
    # For SSL offloading, pass the following header in your proxy server or load balancer: 'X-Forwarded-Proto: https'

    backend default {
        .host = "magento";
        .port = "80";
        .connect_timeout = 5s;
        .first_byte_timeout = 10s;
        .between_bytes_timeout = 10s;
        .probe = {
            .url = "/pub/health_check.php";
            .timeout = 2s;
            .interval = 10s;
            .window = 50;
            .threshold = 5;
        }
    }

    acl purge {
        "localhost";
    }

    sub vcl_recv {
        if (req.method == "PURGE") {
            if (client.ip !~ purge) {
                return (synth(405, "Method not allowed"));
            }
            # To use the X-Pool header for purging varnish during automated deployments, make sure the X-Pool header
            # has been added to the response in your backend server config. This is used, for example, by the
            # capistrano-magento2 gem for purging old content from varnish during it's deploy routine.
            if (!req.http.X-Magento-Tags-Pattern && !req.http.X-Pool) {
                return (synth(400, "X-Magento-Tags-Pattern or X-Pool header required"));
            }
            if (req.http.X-Magento-Tags-Pattern) {
              ban("obj.http.X-Magento-Tags ~ " + req.http.X-Magento-Tags-Pattern);
            }
            if (req.http.X-Pool) {
              ban("obj.http.X-Pool ~ " + req.http.X-Pool);
            }
            return (synth(200, "Purged"));
        }

        if (req.method != "GET" &&
            req.method != "HEAD" &&
            req.method != "PUT" &&
            req.method != "POST" &&
            req.method != "TRACE" &&
            req.method != "OPTIONS" &&
            req.method != "DELETE") {
              /* Non-RFC2616 or CONNECT which is weird. */
              return (pipe);
        }

        # We only deal with GET and HEAD by default
        if (req.method != "GET" && req.method != "HEAD") {
            return (pass);
        }

        # Bypass shopping cart, checkout and search requests
        if (req.url ~ "/checkout" || req.url ~ "/catalogsearch") {
            return (pass);
        }

        # Bypass health check requests
        if (req.url ~ "/pub/health_check.php") {
            return (pass);
        }

        # Set initial grace period usage status
        set req.http.grace = "none";

        # normalize url in case of leading HTTP scheme and domain
        set req.url = regsub(req.url, "^http[s]?://", "");

        # collect all cookies
        std.collect(req.http.Cookie);

        # Compression filter. See https://www.varnish-cache.org/trac/wiki/FAQ/Compression
        if (req.http.Accept-Encoding) {
            if (req.url ~ "\.(jpg|jpeg|png|gif|gz|tgz|bz2|tbz|mp3|ogg|swf|flv)$") {
                # No point in compressing these
                unset req.http.Accept-Encoding;
            } elsif (req.http.Accept-Encoding ~ "gzip") {
                set req.http.Accept-Encoding = "gzip";
            } elsif (req.http.Accept-Encoding ~ "deflate" && req.http.user-agent !~ "MSIE") {
                set req.http.Accept-Encoding = "deflate";
            } else {
                # unknown algorithm
                unset req.http.Accept-Encoding;
            }
        }

        # Remove all marketing get parameters to minimize the cache objects
        if (req.url ~ "(\?|&)(gclid|cx|ie|cof|siteurl|zanpid|origin|fbclid|mc_[a-z]+|utm_[a-z]+|_bta_[a-z]+)=") {
            set req.url = regsuball(req.url, "(gclid|cx|ie|cof|siteurl|zanpid|origin|fbclid|mc_[a-z]+|utm_[a-z]+|_bta_[a-z]+)=[-_A-z0-9+()%.]+&?", "");
            set req.url = regsub(req.url, "[?|&]+$", "");
        }

        # Static files caching
        if (req.url ~ "^/(pub/)?(media|static)/") {
            # Static files should not be cached by default
            return (pass);

            # But if you use a few locales and don't use CDN you can enable caching static files by commenting previous line (#return (pass);) and uncommenting next 3 lines
            #unset req.http.Https;
            #unset req.http.X-Forwarded-Proto;
            #unset req.http.Cookie;
        }

        return (hash);
    }

    sub vcl_hash {
        if (req.http.cookie ~ "X-Magento-Vary=") {
            hash_data(regsub(req.http.cookie, "^.*?X-Magento-Vary=([^;]+);*.*$", "\1"));
        }

        # For multi site configurations to not cache each other's content
        if (req.http.host) {
            hash_data(req.http.host);
        } else {
            hash_data(server.ip);
        }

        # To make sure http users don't see ssl warning
        if (req.http.X-Forwarded-Proto) {
            hash_data(req.http.X-Forwarded-Proto);
        }


        if (req.url ~ "/graphql") {
            call process_graphql_headers;
        }
    }

    sub process_graphql_headers {
        if (req.http.Store) {
            hash_data(req.http.Store);
        }
        if (req.http.Content-Currency) {
            hash_data(req.http.Content-Currency);
        }
    }

    sub vcl_backend_response {

        set beresp.grace = 3d;

        if (beresp.http.content-type ~ "text") {
            set beresp.do_esi = true;
        }

        if (bereq.url ~ "\.js$" || beresp.http.content-type ~ "text") {
            set beresp.do_gzip = true;
        }

        if (beresp.http.X-Magento-Debug) {
            set beresp.http.X-Magento-Cache-Control = beresp.http.Cache-Control;
        }

        # cache only successfully responses and 404s
        if (beresp.status != 200 && beresp.status != 404) {
            set beresp.ttl = 0s;
            set beresp.uncacheable = true;
            return (deliver);
        } elsif (beresp.http.Cache-Control ~ "private") {
            set beresp.uncacheable = true;
            set beresp.ttl = 86400s;
            return (deliver);
        }

        # validate if we need to cache it and prevent from setting cookie
        if (beresp.ttl > 0s && (bereq.method == "GET" || bereq.method == "HEAD")) {
            unset beresp.http.set-cookie;
        }

       # If page is not cacheable then bypass varnish for 2 minutes as Hit-For-Pass
       if (beresp.ttl <= 0s ||
           beresp.http.Surrogate-control ~ "no-store" ||
           (!beresp.http.Surrogate-Control &&
           beresp.http.Cache-Control ~ "no-cache|no-store") ||
           beresp.http.Vary == "*") {
            # Mark as Hit-For-Pass for the next 2 minutes
            set beresp.ttl = 120s;
            set beresp.uncacheable = true;
        }

        return (deliver);
    }

    sub vcl_deliver {
        if (resp.http.X-Magento-Debug) {
            if (resp.http.x-varnish ~ " ") {
                set resp.http.X-Magento-Cache-Debug = "HIT";
                set resp.http.Grace = req.http.grace;
            } else {
                set resp.http.X-Magento-Cache-Debug = "MISS";
            }
        } else {
            unset resp.http.Age;
        }

        # Not letting browser to cache non-static files.
        if (resp.http.Cache-Control !~ "private" && req.url !~ "^/(pub/)?(media|static)/") {
            set resp.http.Pragma = "no-cache";
            set resp.http.Expires = "-1";
            set resp.http.Cache-Control = "no-store, no-cache, must-revalidate, max-age=0";
        }

        unset resp.http.X-Magento-Debug;
        unset resp.http.X-Magento-Tags;
        unset resp.http.X-Powered-By;
        unset resp.http.Server;
        unset resp.http.X-Varnish;
        unset resp.http.Via;
        unset resp.http.Link;
    }

    sub vcl_hit {
        if (obj.ttl >= 0s) {
            # Hit within TTL period
            return (deliver);
        }
        if (std.healthy(req.backend_hint)) {
            if (obj.ttl + 300s > 0s) {
                # Hit after TTL expiration, but within grace period
                set req.http.grace = "normal (healthy server)";
                return (deliver);
            } else {
                # Hit after TTL and grace expiration
                return (restart);
            }
        } else {
            # server is not healthy, retrieve from cache
            set req.http.grace = "unlimited (unhealthy server)";
            return (deliver);
        }
    }

```

Both backend and Varnish are running just fine - it seems:

```
I0720 09:53:18.226042       1 main.go:31] running kube-httpcache with following options: {Kubernetes:{Config: RetryBackoffString:30s RetryBackoff:30s} Frontend:{Address:0.0.0.0 Port:80 Watch:false Namespace:production Service:magento-varnish PortName:http} Backend:{Watch:false Namespace:production Service:magento Port: PortName:http} Signaller:{Enable:true Address:0.0.0.0 Port:8090 WorkersCount:1 MaxRetries:5 RetryBackoffString:30s RetryBackoff:30s} Admin:{Address:0.0.0.0 Port:6083} Varnish:{SecretFile:/etc/varnish/k8s-secret/secret Storage:malloc,512M AdditionalParameters:http_resp_size=98304 VCLTemplate:/etc/varnish/tmpl/default.vcl.tmpl VCLTemplatePoll:false}}
I0720 09:53:18.226207       1 main.go:38] using in-cluster configuration
I0720 09:53:18.227507       1 run.go:15] waiting for initial configuration before starting Varnish
I0720 09:53:18.227848       1 run.go:35] creating initial VCL config
I0720 09:53:18.227959       1 wait.go:12] probing admin port until it is available
Debug: Version: varnish-6.0.6 revision 29a1a8243dbef3d973aec28dc90403188c1dc8e7
Debug: Platform: Linux,4.19.123-coreos,x86_64,-junix,-smalloc,-sdefault,-hcritbit
Debug: Child (29) Started
Info: Child (29) said Child starts
I0720 09:53:21.228543       1 dial.go:41] authentication required. challenge string: "iqtcmzvvljtjtzouppcegioirulcyxqz"
I0720 09:53:21.228560       1 wait.go:23] admin port is available
```

**Environment:**
 - Kubernetes version: 1.17.0
 - kube-httpcache version: quay.io/mittwald/kube-httpcache:stable

Could not find the problem. Another interesting thing for me is that even though I set the following checks:

```
readinessProbe:
            httpGet:
              port: 80
              httpHeaders:
                - name: Host
                  value: example.com
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 80
              httpHeaders:
                - name: Host
                  value: example.com
```

Varnish would still not get restarted by Kubernetes, health checks pass. If Varnish would get restarted as soon as it starts to throw 503s, the site would be down only for a minute.

Thanks for help!
