### ISSUE TITLE
Readiness Probe

### ISSUE THREAD

**Issue by tschirmer** [mittwald/kube-httpcache#34]
**Is your feature request related to a problem? Please describe.**
Without a readiness probe, when upgrading, the new servers produce a front facing downtime between the time they first start up, and the time they're ready to serve (and checking that that backend health checks pass).

**Describe the solution you'd like**
A readiness + liveliness probe setup so that when a rolling update is applied, no downtime can be ensured.

**Describe alternatives you've considered**
Not alternatives are possible within this context, other than planned downtime schedules to work around this issue.

**Comment by tschirmer** [comment]
ok, so I've made a work around. It isn't a full health check + liveliness check, but it will delay the traffic switchover until the child process of varnish has up time.
```
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - if [ $(varnishstat -1 | grep MAIN.uptime | awk -F ' ' '{print $2}') -gt 1 ]; then exit 0; else exit 1; fi
            initialDelaySeconds: 5
            periodSeconds: 5
```

**Comment by tschirmer** [comment]
IN context that looks like:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: output-cache
  namespace: application
  labels:
    app: application
    tier: frontend
spec:
  serviceName: application-frontend-output
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
        app: application
        tier: frontend
  template:
    metadata:
      labels:
        app: application
        tier: frontend
    spec:
      containers:
        - name: cache
          image: quay.io/mittwald/kube-httpcache:v0.3.1
          imagePullPolicy: Always
          ports:
            - name: frontend-port
              containerPort: 6081
              protocol: TCP
            - name: admin-port
              containerPort: 6083
              protocol: TCP
            - name: signaller-port
              containerPort: 8090
              protocol: TCP
          args:
            - -admin-addr=0.0.0.0
            - -admin-port=6083
            - -signaller-enable=true
            - -signaller-port=8090
            - -frontend-watch=true
            - -frontend-port=6081
            - -frontend-namespace=$(NAMESPACE)
            - -frontend-service=storebase-frontend-output
            - -backend-watch=true
            - -backend-namespace=$(NAMESPACE)
            - -backend-service=storebase-app-no-cache
            - -varnish-secret-file=/etc/varnish/k8s-secret/secret
            - -varnish-vcl-template=/etc/varnish/tmpl/default.vcl.tmpl
            - -varnish-storage=malloc,128M
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - if [ $(varnishstat -1 | grep MAIN.uptime | awk -F ' ' '{print $2}') -gt 1 ]; then exit 0; else exit 1; fi
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: template
              mountPath: /etc/varnish/tmpl
            - name: secret
              mountPath: /etc/varnish/k8s-secret
      serviceAccountName: kube-httpcache  # when using RBAC
      automountServiceAccountToken: true
      restartPolicy: Always
      volumes:
        - name: template
          configMap:
            name: vcl-template
        - name: secret
          secret:
            secretName: varnish-secret
```
