### ISSUE TITLE
Varnishd does not start, defauly.vcl is not updated, No errors in logs.

### ISSUE THREAD

**Issue by navidnadali** [mittwald/kube-httpcache#40]
**Describe the bug**
Note: This is probably not a bug but we have marked as bug for lack of a better classification. 

We are trying to deploy kube-httpcache into GKE (1.16.13-gke.1).

We have deployed as per the instructions and unfortunately the varnishd is never started. We assume this is because there is potentially an error in the config map template and when this is being converted to the default.vcl the issue arises. However we are using the config map as per instructions (we do have our own VCL but we have not deployed that at this stage).

We note that the default.vcl contents is never updated and it contains the default values.

We note that we have also tried with and without the varnish-vcl-template-poll with no luck. 

Pod Logs:

```
I0903 14:47:12.360019       1 main.go:31] running kube-httpcache with following options: {Kubernetes:{Config: RetryBackoffString:30s RetryBackoff:30s} Frontend:{Address:0.0.0.0 Port:80 Watch:false Namespace:aphrodite1994-m2-aphrodite1994-com Service:frontend-service PortName:http} Backend:{Watch:true Namespace:aphrodite1994-m2-aphrodite1994-com Service:backend-service Port: PortName:http} Signaller:{Enable:true Address:0.0.0.0 Port:8090 WorkersCount:1 MaxRetries:5 RetryBackoffString:30s RetryBackoff:30s} Admin:{Address:0.0.0.0 Port:6083} Varnish:{SecretFile:/etc/varnish/k8s-secret/secret Storage:malloc,128M AdditionalParameters: VCLTemplate:/etc/varnish/tmpl/default.vcl.tmpl VCLTemplatePoll:true} Readiness:{Enable:true Address:0.0.0.0:9102}}
I0903 14:47:12.360266       1 main.go:38] using in-cluster configuration
I0903 14:47:12.362767       1 run.go:15] waiting for initial configuration before starting Varnish
E0903 14:47:12.371195       1 endpoints_watch.go:29] error while establishing watch: unknown (get endpoints)
I0903 14:47:12.371216       1 endpoints_watch.go:30] retrying after 30s
E0903 14:47:42.374661       1 endpoints_watch.go:29] error while establishing watch: unknown (get endpoints)
I0903 14:47:42.374703       1 endpoints_watch.go:30] retrying after 30s
```

**To Reproduce**
1. Create yaml files provided
2. Deploy yaml files provided
3. Note that varnishd service is never started.

**Expected behavior**

1. kube-httpcache to start varnishd as expected.

**Environment:**
 - Kubernetes version: 1.16.13-gke.1
 - kube-httpcache version: master

**Configuration**

varnish.yaml

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache-statefulset
  labels:
    app: cache
spec:
  serviceName: cache-service
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image: quay.io/mittwald/kube-httpcache:stable
        imagePullPolicy: Always
        args:
        - -admin-addr=0.0.0.0
        - -admin-port=6083
        - -signaller-enable
        - -signaller-port=8090
        - -frontend-namespace=$(NAMESPACE)
        - -frontend-service=frontend-service
        - -backend-namespace=$(NAMESPACE)
        - -backend-service=backend-service
        - -varnish-secret-file=/etc/varnish/k8s-secret/secret
        - -varnish-vcl-template=/etc/varnish/tmpl/default.vcl.tmpl
        - -varnish-vcl-template-poll=true
        - -varnish-storage=malloc,128M
        - -log_dir=/var/log/varnish
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: template
          mountPath: /etc/varnish/tmpl
        - name: secret
          mountPath: /etc/varnish/k8s-secret
      restartPolicy: Always
      volumes:
      - name: template
        configMap:
          name: vcl-template
      - name: secret
        secret:
          secretName: varnish-secret
```

varnish-config.yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: vcl-template
data:
  default.vcl.tmpl: |
    vcl 4.0;

    import std;
    import directors;

    // ".Frontends" is a slice that contains all known Varnish instances
    // (as selected by the service specified by -frontend-service).
    // The backend name needs to be the Pod name, since this value is compared
    // to the server identity ("server.identity" [1]) later.
    //
    //   [1]: https://varnish-cache.org/docs/6.4/reference/vcl.html#local-server-remote-and-client
    {{ range .Frontends }}
    backend {{ .Name }} {
        .host = "{{ .Host }}";
        .port = "{{ .Port }}";
    }
    {{- end }}

    backend fe-primary {
        .host = "{{ .PrimaryFrontend.Host }}";
        .port = "{{ .PrimaryFrontend.Port }}";
    }

    {{ range .Backends }}
    backend be-{{ .Name }} {
        .host = "{{ .Host }}";
        .port = "{{ .Port }}";
    }
    {{- end }}

    backend be-primary {
        .host = "{{ .PrimaryBackend.Host }}";
        .port = "{{ .PrimaryBackend.Port }}";
    }

    acl purgers {
        "127.0.0.1";
        "localhost";
        "::1";
        {{- range .Frontends }}
        "{{ .Host }}";
        {{- end }}
        {{- range .Backends }}
        "{{ .Host }}";
        {{- end }}
    }

    sub vcl_init {
        new cluster = directors.hash();

        {{ range .Frontends -}}
        cluster.add_backend({{ .Name }}, 1);
        {{ end }}

        new lb = directors.round_robin();

        {{ range .Backends -}}
        lb.add_backend(be-{{ .Name }});
        {{ end }}
    }

    sub vcl_recv
    {
        # Set backend hint for non cachable objects.
        set req.backend_hint = lb.backend();

        # ...

        # Routing logic. Pass a request to an appropriate Varnish node.
        # See https://info.varnish-software.com/blog/creating-self-routing-varnish-cluster for more info.
        unset req.http.x-cache;
        set req.backend_hint = cluster.backend(req.url);
        set req.http.x-shard = req.backend_hint;
        if (req.http.x-shard != server.identity) {
            return(pass);
        }
        set req.backend_hint = lb.backend();

        # ...

        return(hash);
    }
```

Any help and/or insight is greatly appreciated
